version: "3.5"

services:
  api:
    container_name: checkbdapi
    image: checkbdapi:latest
    environment:
      DB_HOST: postgres
      DB_NAME: dockdatabase
    restart: always
    build:
      context: .
      target: backend
    ports:
      - 9091:9091
    networks:
      - proxynet
networks:
  proxynet:
    external: true
    name: internal-network